/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgecon;

import javax.swing.JFrame;
import sisgecon.telas.TelaComunicCond;
import sisgecon.telas.TelaAreasComuns;
import sisgecon.telas.TelaBoleto;
import sisgecon.telas.TelaReclamacaoCondo;

/**
 *
 * @author thalytaveiga
 */
public class SistemaCond extends javax.swing.JFrame {

    TelaAreasComuns telaAreasComuns;
    TelaComunicCond telaComunicCond;
    TelaReclamacaoCondo telaReclamacaoCondo;
    TelaBoleto telaBoleto;
    
    /**
     * Creates new form SistemaCond
     */
    public SistemaCond() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArea = new javax.swing.JMenu();
        telarAreaComum = new javax.swing.JMenuItem();
        jMenuComunic = new javax.swing.JMenu();
        telaComunicados = new javax.swing.JMenuItem();
        jMenuReclam = new javax.swing.JMenu();
        telaReclamacoes = new javax.swing.JMenuItem();
        jMenuBoleto = new javax.swing.JMenu();
        imprimirBoleto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(619, 418));

        jMenuArea.setText("Áreas Comuns");
        jMenuArea.setSize(new java.awt.Dimension(25, 20));

        telarAreaComum.setText("Consultar");
        telarAreaComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telarAreaComumActionPerformed(evt);
            }
        });
        jMenuArea.add(telarAreaComum);

        jMenuBar.add(jMenuArea);

        jMenuComunic.setText("Comunicados");

        telaComunicados.setText("Ver comunicados");
        telaComunicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaComunicadosActionPerformed(evt);
            }
        });
        jMenuComunic.add(telaComunicados);

        jMenuBar.add(jMenuComunic);

        jMenuReclam.setText("Reclamações");

        telaReclamacoes.setText("Registrar");
        telaReclamacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaReclamacoesActionPerformed(evt);
            }
        });
        jMenuReclam.add(telaReclamacoes);

        jMenuBar.add(jMenuReclam);

        jMenuBoleto.setText("Boleto");

        imprimirBoleto.setText("Imprimir");
        imprimirBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBoletoActionPerformed(evt);
            }
        });
        jMenuBoleto.add(imprimirBoleto);

        jMenuBar.add(jMenuBoleto);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telarAreaComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telarAreaComumActionPerformed
    // Abre a tela de áreas comuns para fazer reserva    
  
        if (telaAreasComuns == null) {
                telaAreasComuns = new TelaAreasComuns();
        jDesktopPane1.add(telaAreasComuns);
        telaAreasComuns.setVisibleBtnCancelar(false);
        telaAreasComuns.setVisible(true);
        }
        else
            telaAreasComuns.show();
        
    }//GEN-LAST:event_telarAreaComumActionPerformed

    private void telaComunicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaComunicadosActionPerformed
        // Abre a tela de comunicados
        
        if (telaComunicCond == null) {
                telaComunicCond = new TelaComunicCond();
        jDesktopPane1.add(telaComunicCond);
        telaComunicCond.setVisible(true);
        }
        else
            telaComunicCond.show();
 
        
    }//GEN-LAST:event_telaComunicadosActionPerformed

    private void telaReclamacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaReclamacoesActionPerformed
        // Mostra a tela de reclamações
        
        if (telaReclamacaoCondo == null) {
                telaReclamacaoCondo = new TelaReclamacaoCondo();
        jDesktopPane1.add(telaReclamacaoCondo);
        telaReclamacaoCondo.setVisible(true);
        }
        else
            telaReclamacaoCondo.show();
        
    }//GEN-LAST:event_telaReclamacoesActionPerformed

    private void imprimirBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBoletoActionPerformed
        // Mostra a tela para gerar boleto
        
       if (telaBoleto == null) {
                telaBoleto = new TelaBoleto();
        jDesktopPane1.add(telaBoleto);
        telaBoleto.setVisible(true);
       }
       else
           telaBoleto.show();
        
    }//GEN-LAST:event_imprimirBoletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaCond().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imprimirBoleto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuArea;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuBoleto;
    private javax.swing.JMenu jMenuComunic;
    private javax.swing.JMenu jMenuReclam;
    private javax.swing.JMenuItem telaComunicados;
    private javax.swing.JMenuItem telaReclamacoes;
    private javax.swing.JMenuItem telarAreaComum;
    // End of variables declaration//GEN-END:variables
}
