/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgecon.telas;

import sisgecon.SistemaAdm;
import sisgecon.SistemaCond;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sisgecon.UsuarioLogado;
import sisgecon.dao.AreasComunsDAO;
import sisgecon.dao.UsuarioDAO;
import sisgecon.vo.AreasComunsVO;
import sisgecon.vo.UsuarioVO;

/**
 *
 * @author thalytaveiga
 */
public class TelaAreasComuns extends javax.swing.JInternalFrame {

    private AreasComunsVO areascomunsVO;
    /**
     * Creates new form TelaAreasComuns
     */
    public TelaAreasComuns() {
        initComponents();
        areascomunsVO = new AreasComunsVO();
        btnCancelarReserva.setEnabled(false);
        btnReservar.setEnabled(false);
        if(UsuarioLogado.getInstance().getUsuarioVO().getIdTipoUsuario() == 1){
            lblSelectArea1.setVisible(true);
            cbArea1.setVisible(true);
            try {
                UsuarioDAO usuarioDAO = new UsuarioDAO();
                //DefaultComboBoxModel model = new DefaultComboBoxModel();
                //for (UsuarioVO usr : usuarioDAO.getUsuarios())
                //    model.addElement(usr.getNome());
                //cbArea1.setModel(model);
                cbArea1.setModel(new DefaultComboBoxModel(usuarioDAO.getUsuarios().toArray()));
                
            } catch (SQLException ex) {
                Logger.getLogger(TelaAreasComuns.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            lblSelectArea1.setVisible(false);
            cbArea1.setVisible(false);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSelectArea = new javax.swing.JLabel();
        lblSelectData = new javax.swing.JLabel();
        cbArea = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        btnConsultar = new javax.swing.JButton();
        jtfStatus = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();
        cbArea1 = new javax.swing.JComboBox<>();
        lblSelectArea1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Áreas comuns");

        lblSelectArea.setText("Área");

        lblSelectData.setText("Data");

        cbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salão de festas", "Churrasqueira" }));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jtfStatus.setEditable(false);
        jtfStatus.setColumns(15);

        lblStatus.setText("Status");

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnCancelarReserva.setText("Cancelar reserva");
        btnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservaActionPerformed(evt);
            }
        });

        lblSelectArea1.setText("Condômino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(lblSelectData)
                            .addComponent(lblSelectArea))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSelectArea1)
                        .addGap(18, 18, 18)
                        .addComponent(cbArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelectArea1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelectArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSelectData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed
        // Cancelar reserva.
        
        try {
            AreasComunsDAO areascomunsDAO = new AreasComunsDAO();
            areascomunsDAO.deletarReserva(areascomunsVO);
        
        } 
        
        catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // Reserva a área na data selecionada.
        
       if (jtfStatus.getText().equals("Indisponível")) {
           JOptionPane.showMessageDialog(rootPane, "Area indisponível na data selecionada. "
                   + "Por favor, selecione outra data.", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
       }
       else {
        
        popularAreasComunsVO();
       
        
        try {
            AreasComunsDAO areascomunsDAO = new AreasComunsDAO ();
            areascomunsDAO.cadastrarAreasComuns(this.areascomunsVO);
            JOptionPane.showMessageDialog(null,"Cadastro efetuado com sucesso!");
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(TelaAreasComuns.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro no cadastro!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
        }
       }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Consulta no banco se a área já está reservada ou não na data selecionada.
         if(jDateChooser.getDate() == null)
             JOptionPane.showMessageDialog(rootPane, "Selecione uma data!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
         else{
             
            try {

            AreasComunsDAO areascomunsDAO = new AreasComunsDAO();
            areascomunsVO = areascomunsDAO.consultarArea(cbArea.getSelectedIndex(), jDateChooser.getDate());
            jtfStatus.setText(areascomunsVO.getSituacao());

            } 

            catch (Exception e) {
                e.printStackTrace();
            }


            if (jtfStatus.getText().equals("Disponível")){
                btnCancelarReserva.setEnabled(false);
                btnReservar.setEnabled(true);
            }
            else{
                btnCancelarReserva.setEnabled(true);
                btnReservar.setEnabled(false);
            }
         }
    }//GEN-LAST:event_btnConsultarActionPerformed

public void setVisibleBtnCancelar(Boolean botaocancelar) {
    btnCancelarReserva.setVisible(botaocancelar);
}

private AreasComunsVO popularAreasComunsVO () {
        
        areascomunsVO.setIdArea(cbArea.getSelectedIndex());
        areascomunsVO.setData(jDateChooser.getDate());
        if(UsuarioLogado.getInstance().getUsuarioVO().getIdTipoUsuario() == 2)
            areascomunsVO.setIdUsuarioReserva(UsuarioLogado.getInstance().getUsuarioVO().getId());
        else
            areascomunsVO.setIdUsuarioReserva(((UsuarioVO)cbArea1.getSelectedItem()).getId());
       
        return areascomunsVO;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> cbArea;
    private javax.swing.JComboBox<String> cbArea1;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfStatus;
    private javax.swing.JLabel lblSelectArea;
    private javax.swing.JLabel lblSelectArea1;
    private javax.swing.JLabel lblSelectData;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
