/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgecon.telas;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sisgecon.UsuarioLogado;
import sisgecon.dao.ReclamacoesDAO;
import sisgecon.vo.ReclamacoesVO;

/**
 *
 * @author thalytaveiga
 */
public class TelaReclamacaoCondo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormReclamacao
     */
    public TelaReclamacaoCondo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoReclam = new javax.swing.JTextArea();
        btnEnviarReclam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);
        setTitle("Reclamações");

        textoReclam.setColumns(20);
        textoReclam.setRows(5);
        jScrollPane1.setViewportView(textoReclam);

        btnEnviarReclam.setText("Enviar");
        btnEnviarReclam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarReclamActionPerformed(evt);
            }
        });

        jLabel1.setText("Título");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnEnviarReclam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarReclam, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarReclamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarReclamActionPerformed
        if(validar() == true){
            ReclamacoesDAO reclamacoesDAO;
            try {
                reclamacoesDAO = new ReclamacoesDAO();
                reclamacoesDAO.inserir(popularReclamacaoVO());
                JOptionPane.showMessageDialog(null,"Cadastro efetuado com sucesso!");
            } catch (SQLException ex) {
                Logger.getLogger(TelaComunicAdm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            limpar();
        }
    }//GEN-LAST:event_btnEnviarReclamActionPerformed

    private ReclamacoesVO popularReclamacaoVO () {
            
        ReclamacoesVO reclamacoesVO = new ReclamacoesVO();
        reclamacoesVO.setReclamacao(jTextField1.getText());
        reclamacoesVO.setDataReclamacao(new Date());
        reclamacoesVO.setIdUsuarioReclamacao(UsuarioLogado.getInstance().getUsuarioVO().getId());
             
        return reclamacoesVO;
    }
    
    private void limpar(){
        jTextField1.setText("");
        textoReclam.setText("");
    }
    
    private boolean validar(){
        if("".equals(jTextField1.getText())){
            JOptionPane.showMessageDialog(rootPane, "Campo Titulo obrigatorio!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
            return false;
        }
        
        if("".equals(textoReclam.getText())){
            JOptionPane.showMessageDialog(rootPane, "Campo Reclamacao obrigatorio!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarReclam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea textoReclam;
    // End of variables declaration//GEN-END:variables
}
