/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgecon.telas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import sisgecon.PrimeiroCadastro;
import sisgecon.SistemaAdm;
import sisgecon.SistemaCond;
import sisgecon.UsuarioLogado;
import sisgecon.dao.UsuarioDAO;
import sisgecon.vo.UsuarioVO;

/**
 *
 * @author thalytaveiga
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnEntrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSisgecon = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jpasswordSenha = new javax.swing.JPasswordField();
        jffCpf = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##");
            jffCpf = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){ }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblSisgecon.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        lblSisgecon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisgecon/telas/if_app_type_tourist_512px_GREY_287493.png"))); // NOI18N
        lblSisgecon.setText(" SISGECON");

        lblCpf.setText("CPF");

        lblSenha.setText("Senha");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jpasswordSenha.setColumns(20);
        jpasswordSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordSenhaActionPerformed(evt);
            }
        });

        jffCpf.setColumns(20);
        try {
            jffCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jffCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jffCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSisgecon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpf)
                        .addGap(26, 26, 26)
                        .addComponent(jffCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lblSisgecon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(jffCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(jpasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
                    
        UsuarioVO usuarioVO = null;
            
        try {
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            usuarioVO=usuarioDAO.getUsuarioCPF(jffCpf.getText().replace(".","").replace("-",""));
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Usuário inválido!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
        }
        
        
        if (validarLogin(usuarioVO)){
            
            if (!validaCadastro(usuarioVO)){
                PrimeiroCadastro cadastrar = new PrimeiroCadastro(usuarioVO);
                cadastrar.setVisible(true);
                //dispose();
            }
            
            else
                if (usuarioVO.getIdTipoUsuario()==1){
                     SistemaAdm sistemaadm = new SistemaAdm();
                     sistemaadm.setVisible(true);
                     //dispose();
                }
                
                else {
                    SistemaCond sistemacond = new SistemaCond();
                    sistemacond.setVisible(true);
                }
            dispose();
        
        }
        
        else {
            // Mostra mensagem de erro ao digitar senha ou CPF inválidos.
                JOptionPane.showMessageDialog(rootPane, "CPF ou senha inválidos!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
                
                }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private boolean validarLogin (UsuarioVO usuarioVO){
        String password = new String(jpasswordSenha.getPassword());
            if (jffCpf.getText().replace(".", "").replace("-", "").equals(usuarioVO.getCpf()) && 
                password.equals(usuarioVO.getSenha())){
                UsuarioLogado.getInstance().setUsuarioVO(usuarioVO);
                return true;
            }
                
        
        else
            return false;
    }
    
    private boolean validaCadastro (UsuarioVO usuarioVO){    
        if (null == usuarioVO.getApto())
            return false;
        if (null == usuarioVO.getCelular())
            return false;
        if (null == usuarioVO.getNome())
            return false;
        
        return true;
    }
    
    private void jpasswordSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordSenhaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jpasswordSenhaActionPerformed

    public JPasswordField getjPasswordField1() {
        return jpasswordSenha;
    }

    public void setjPasswordField1(JPasswordField jPasswordField1) {
        this.jpasswordSenha = jPasswordField1;
    }

    private void jffCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jffCpfActionPerformed

    }//GEN-LAST:event_jffCpfActionPerformed

    public JFormattedTextField getjFormattedTextField1() {
        return jffCpf;
    }

    public void setjFormattedTextField1(JFormattedTextField jFormattedTextField1) {
        this.jffCpf = jFormattedTextField1;
    }

    
     // Verifica no banco se o usuário está com o cadastro completo. Se estiver, vai direto para o sistema.
    // Se não estiver completo, mostra a tela para completar o cadastro.
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JFormattedTextField jffCpf;
    private javax.swing.JPasswordField jpasswordSenha;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSisgecon;
    // End of variables declaration//GEN-END:variables
}
