/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgecon.telas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sisgecon.dao.UsuarioDAO;
import sisgecon.vo.UsuarioVO;

/**
 *
 * @author thalytaveiga
 */
public class TelaCadastroCPF extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCPF
     */
    public TelaCadastroCPF() {
        initComponents();
        
        // O sistema apresenta diferentes funcionalidades para 2 tipos de usuário.
        /* if (rdbtnAdm.isSelected()){
        SistemaAdm entrasistema = new SistemaAdm();
        entrasistema.setVisible(true);
        }
        
        else {
        SistemaCond entrasistemacond = new SistemaCond();
        entrasistemacond.setVisible(true);
        } */
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoUsuario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        jbtnCadastrar = new javax.swing.JButton();
        lblSenhaPadrao = new javax.swing.JLabel();
        jpasswordfield = new javax.swing.JPasswordField();
        jftfCpf = new javax.swing.JFormattedTextField();
        rdAdministrativo = new javax.swing.JRadioButton();
        rdCondomino = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Cadastrar Usuário");

        lblCpf.setText("CPF");

        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });

        lblSenhaPadrao.setText("Senha Padrão");

        jpasswordfield.setColumns(15);

        jftfCpf.setColumns(15);
        try {
            jftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnGroupTipoUsuario.add(rdAdministrativo);
        rdAdministrativo.setText("Administrativo");

        btnGroupTipoUsuario.add(rdCondomino);
        rdCondomino.setSelected(true);
        rdCondomino.setText("Condômino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSenhaPadrao)
                            .addComponent(lblCpf))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(rdAdministrativo)
                        .addGap(75, 75, 75)
                        .addComponent(rdCondomino)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnCadastrar)
                .addGap(198, 198, 198))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaPadrao)
                    .addComponent(jpasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdAdministrativo)
                    .addComponent(rdCondomino))
                .addGap(18, 18, 18)
                .addComponent(jbtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
      
        UsuarioVO usuarioVO = popularUsuarioVO();
        
      if (validarCampos(popularUsuarioVO())){
          
          try {
              UsuarioDAO usuarioDAO = new UsuarioDAO();
              usuarioDAO.inserirCpf(usuarioVO);
              JOptionPane.showMessageDialog(rootPane, "CPF cadastrado com sucesso!");
              jftfCpf.setText("");
              jpasswordfield.setText("");
              //JOptionPane.showConfirmDialog(rootPane, closable);
          } 
          
          catch (SQLException ex) {
              Logger.getLogger(TelaCadastroCPF.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(rootPane, "Erro no cadastro!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
          }
          
          
      }
        
        
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private UsuarioVO popularUsuarioVO () {
    
        UsuarioVO usuarioVO = new UsuarioVO();
        
        usuarioVO.setCpf(jftfCpf.getText());
        usuarioVO.setSenha(jpasswordfield.getText());
        
        if (rdAdministrativo.isSelected())
            usuarioVO.setIdTipoUsuario(1);
        else
            usuarioVO.setIdTipoUsuario(2);
       
        return usuarioVO;
    }
    
    private boolean validarCampos (UsuarioVO usuarioVO){
        
        if ("".equals(usuarioVO.getCpf().replace(".","").replace("-",""))){
            JOptionPane.showMessageDialog(rootPane, "Campo CPF obrigatório!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
            return false;
        }
         if ("".equals(usuarioVO.getSenha())){
            JOptionPane.showMessageDialog(rootPane, "Campo Senha obrigatório!", 
                        "ERRO", JOptionPane.ERROR_MESSAGE, null);
            return false;
        }

            return true;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTipoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JPasswordField jpasswordfield;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblSenhaPadrao;
    private javax.swing.JRadioButton rdAdministrativo;
    private javax.swing.JRadioButton rdCondomino;
    // End of variables declaration//GEN-END:variables
    
}
